# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoLivreApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoLivreApp
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'MBProgressHUD'

  target 'MercadoLivreAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MercadoLivreAppUITests' do
    # Pods for testing
  end

end
